# Generated by Django 4.2.30 on 2026-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusers',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
