# Generated by Django 4.2.30 on 2026-05-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_share_like_comment_share_unique_post_share_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to='core.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_post_shares', to='core.fusers')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_post_shares', to='core.fusers')),
            ],
        ),
        migrations.AddConstraint(
            model_name='postshare',
            constraint=models.UniqueConstraint(fields=('post', 'sender', 'recipient'), name='unique_post_share_recipient'),
        ),
    ]
