# Generated by Django 4.2.30 on 2026-05-30 10:51

from django.db import migrations, models


def copy_profile_data(apps, schema_editor):
    FUsers = apps.get_model("core", "FUsers")
    Profile = apps.get_model("core", "Profile")

    for profile in Profile.objects.select_related("user").prefetch_related("followers").all():
        user = profile.user
        user.bio = profile.bio or user.bio
        user.avatar = profile.avatar or user.avatar
        user.location = profile.location or user.location
        user.website = profile.website or user.website
        user.save(update_fields=["bio", "avatar", "location", "website"])
        user.followers.add(*profile.followers.all())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_postshare_postshare_unique_post_share_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusers',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fusers',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fusers',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='core.fusers'),
        ),
        migrations.AddField(
            model_name='fusers',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fusers',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(copy_profile_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
