# Generated by Django 4.2.30 on 2026-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_make_inboxmessage_post_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='fusers',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
