# Generated by Django 4.2.30 on 2026-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_inboxmessage_options_fusers_avatar_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
